### PR TITLE
feat(gcs): add support for GCS storage

### PR DESCRIPTION
**Pull request by smothiki**
Now works for GCS credentials

### CODE REVIEW

**Comment by smothiki** [comment]
```
Starting pod dockerbuild-breezy-unicycle-0dd32b0c-e9f34f2c
Pod spec: {
  "metadata": {
    "name": "dockerbuild-breezy-unicycle-0dd32b0c-e9f34f2c",
    "namespace": "deis",
    "creationTimestamp": null,
    "labels": {
      "heritage": "dockerbuild-breezy-unicycle-0dd32b0c-e9f34f2c"
    }
  },
  "spec": {
    "volumes": [
      {
        "name": "minio-user",
        "secret": {
          "secretName": "minio-user"
        }
      },
      {
        "name": "docker-socket",
        "hostPath": {
          "path": "/var/run/docker.sock"
        }
      }
    ],
    "containers": [
      {
        "name": "deis-dockerbuilder",
        "image": "smothiki/dockerbuilder:v1.3",
        "env": [
          {
            "name": "DEBUG",
            "value": "1"
          },
          {
            "name": "ACCESS_KEY_FILE",
            "value": "/var/run/secrets/object/store/access_key"
          },
          {
            "name": "ACCESS_SECRET_FILE",
            "value": "/var/run/secrets/object/store/access_secret"
          },
          {
            "name": "TAR_URL",
            "value": "https://storage.googleapis.com/planther/home/breezy-unicycle:git-0dd32b0c/tar"
          },
          {
            "name": "IMG_NAME",
            "value": "breezy-unicycle:git-0dd32b0c"
          },
          {
            "name": "REGION",
            "value": "us-east-1"
          }
        ],
        "resources": {},
        "volumeMounts": [
          {
            "name": "minio-user",
            "readOnly": true,
            "mountPath": "/var/run/secrets/object/store"
          },
          {
            "name": "docker-socket",
            "mountPath": "/var/run/docker.sock"
          }
        ],
        "imagePullPolicy": "Always"
      }
    ],
    "restartPolicy": "Never",
    "serviceAccountName": ""
  },
  "status": {}
}

download tar file complete
extracting tar file complete
Step 1 : FROM alpine:3.1
 ---> 1a2ae6f4d377
Step 2 : RUN apk add -U     bash    nginx   && rm -rf /var/cache/apk*
 ---> Running in 028588c325ad
fetch http://dl-cdn.alpinelinux.org/alpine/v3.1/main/x86_64/APKINDEX.tar.gz
(1/6) Installing ncurses-terminfo-base (5.9-r3)
```

**Comment by arschles** [comment]
@bacongobbler can you review this and tell whether the boto addition may cause the same issue that you saw in deis/database related to https://github.com/deis/charts/pull/142?

**Comment by arschles** [comment]
@smothiki code LGTM

**Comment by bacongobbler** [comment]
Seems fine. The issue occurs with minio since minio requires s3v4 and us-east-1, which you will hit https://github.com/boto/boto/issues/2624.

**Comment by smothiki** [comment]
Yeah for minio I'm using boto3 which worked fine. Also boto2 is only for GCS access

**Comment by bacongobbler** [comment]
In the future we should just use boto3 for all the things so we're consistent, but this looks fine to ship for beta IMO.

**Comment by smothiki** [comment]
Boto3 doesn't work for GCS reason to introduce boto2 . In the future this code moves to GO and will be using a Storage facede to support all possible storage backends.

**Comment by arschles** [comment]
@smothiki please add an issue if you're planning on migrating this code to Go. #5 and #3 look tangentially related to that work.

**Comment by smothiki** [comment]
Sure

**Comment by arschles** [comment]
@smothiki does this need manual testing? If so, can you post some testing instructions?

**Comment by smothiki** [comment]
I have manually tested this and it worked or you can use the pasted sample POD information above and see if the POD ended with an exit code zero.

**Comment by arschles** [comment]
@smothiki I trust you, and code LGTM. This PR is ready to merge

**Comment by smothiki** [comment]
thanks

**Pull request merged**
