### PR TITLE
fix(encode): decode chunk to unicode

### LINKED ISSUE #49: Errors if unicode in Job output
When the Dockerfile produces Unicode output (i believe npm install prints a check sign or something) I get this error:

```
Traceback (most recent call last):
  File "/deploy.py", line 106, in <module>
    log_output(stream, True)
  File "/deploy.py", line 25, in log_output
    print(stream_chunk.replace('\n', ''))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 264-266: ordinal not in range(128)
size of streamed logs 2173
Waiting for the deis/dockerbuild-valued-quadrant-febcad02-8068a452 pod to end. Checking every 100ms for 15m0s
Done
remote: 2016/04/19 17:09:05 Error running git receive hook [Build pod exited with code 1, stopping build.]
Checking for builder pod exit code
To ssh://git@deis.10.2.47.19.xip.io:2222/valued-quadrant.git
   d9c7b3a..febcad0  1.3 -> 1.3
```

I believe it is this line:
https://github.com/deis/dockerbuilder/blob/60662962262e9088ce6bf6697c9e89493076b8d1/rootfs/deploy.py#L25

DEBUG is 1

### PR DESCRIPTION
**Pull request by smothiki**
Just tested working 
closes https://github.com/deis/dockerbuilder/issues/49

### CODE REVIEW

**Comment by arschles** [comment]
code LGTM, pending unit tests

**Comment by mboersma** [comment]
Can we write an e2e or unit test to cover this case?

**Comment by smothiki** [comment]
to test this use smothiki/dockerbuilder:v2.4 image in builder-rc.yalm

**Comment by smothiki** [comment]
```
FROM nodesource/wheezy:0.10.36
MAINTAINER Ryan Grieve <ryan@REMOVED.com>

RUN npm install -g webpack
RUN npm install -g webpack-dev-server

WORKDIR /app

EXPOSE 8080
```

Dockerfile to test with

**Comment by mboersma** [comment]
Using the unicode output added in deis/example-dockerfile-http#8, I was able to verify the broken behavior described in #49 and also verify that this PR fixes it. Since the e2e tests always deploy example-dockerfile-http, this effectively creates e2e coverage for this change, although I admit it's indirect--I'm open to better ideas.

In conjunction with deis/example-dockerfile-http#8, I'm ok with this change. @arschles does that seem good enough to you?

**Comment by arschles** [comment]
@mboersma yes, I'm ok with this change along with deis/example-dockerfile-http#8

**Pull request merged**
