### PR TITLE
feat(registry): Allow FROM to refer to the off-cluster docker registry. 

### LINKED ISSUE #100: Support for pulling a private FROM
When workflow is configured to use a private registry the dockerbuilder doesn't provide any authentication to the docker client when building so private FROM images can't be pulled.

Expected behaviour is that shared base images are pulled using the authentication details configured for the off-cluster registry.

Actual behaviour:

No authentication details are available to the client used to build:

```
Starting build... but first, coffee!
Step 1 : FROM quay.io/clearbit/ruby:2.1.10
Error: Status 403 trying to pull repository clearbit/ruby: "{\"error\": \"Permission Denied\"}"
remote: 2016/09/29 09:49:09 Error running git receive hook [Build pod exited with code 1, stopping build.]
```

One possible solution would be to share a docker.Client() between the build and push and call client.login prior to building, rather than passing auth details through to the push specifically in https://github.com/deis/dockerbuilder/blob/master/rootfs/deploy.py#L69

### PR DESCRIPTION
**Pull request by robholland**
Authenticate to off-cluster registries before building so that the client is able to pull private images specified in the FROM.

Fixes #100

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by bacongobbler** [comment]
IIRC there was a specific reason @kmala made it so we attach auth credentials when pushing rather than logging into the registry. @kmala, is there a reason for that logic or does this LGTY?

**Comment by bacongobbler** [comment]
If you wouldn't mind amending your commit such that it follows the [commit style guide](https://deis.com/docs/workflow/contributing/submitting-a-pull-request/#commit-style), that would be awesome! That way it'll get picked up by `deisrel` when we generate the release changelog. Thanks!

**Comment by robholland** [comment]
Yep, I'll reformat, sorry.

If it helps for testing the image is available at quay.io/clearbit/dockerbuilder:canary

**Comment by kmala** [comment]
Jenkins, add to Whitelist

**Comment by kmala** [comment]
I was assuming the login() will write the creds to the filesystem but thats not true and `docker login` does this explicitly https://github.com/docker/docker/blob/e8b9f38c7e2e249084c78c81f136c6d22432af6f/cli/command/registry/login.go#L77.

i had tested this PR by building/pushing an image and also verifying that i can't push the same image from the host on which the build happened.

**Comment by bacongobbler** [comment]
Attached the "needs rebase" label to note amending the commit first before merging.

**Pull request merged**
